name: Run Jest tests

# event
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# tasks
jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
